version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
